module.exports = [
  { data: { name: 'SUV'}, path: '/body-styles' },
  { data: { name: 'Truck'}, path: '/body-styles' },
  { data: { name: 'Van'}, path: '/body-styles' },
  { data: { name: 'Coupe'}, path: '/body-styles' },
  { data: { name: 'Wagon'}, path: '/body-styles' },
  { data: { name: 'Convertible'}, path: '/body-styles' },
  { data: { name: 'Diesel'}, path: '/body-styles' },
  { data: { name: 'Crossover'}, path: '/body-styles' },
  { data: { name: 'Luxury Car'}, path: '/body-styles' },
  { data: { name: 'Hybrid'}, path: '/body-styles' },
  { data: { name: 'Electric'}, path: '/body-styles' },

  { data: { name: 'Tan' }, path: '/colors' },
  { data: { name: 'White' }, path: '/colors' },
  { data: { name: 'Teal' }, path: '/colors' },
  { data: { name: 'Gray' }, path: '/colors' },
  { data: { name: 'Blue' }, path: '/colors' },
  { data: { name: 'Red' }, path: '/colors' },
  { data: { name: 'Brown' }, path: '/colors' },
  { data: { name: 'Gold' }, path: '/colors' },
  { data: { name: 'Green' }, path: '/colors' },
  { data: { name: 'Maroon' }, path: '/colors' },
  { data: { name: 'Orange' }, path: '/colors' },
  { data: { name: 'Purple' }, path: '/colors' },
  { data: { name: 'Pink' }, path: '/colors' },
  { data: { name: 'Yellow' }, path: '/colors' },

  { data: { name: 'Alfa Romeo' }, path: '/makes' },
  { data: { name: 'Aston Martin' }, path: '/makes' },
  { data: { name: 'Austin' }, path: '/makes' },
  { data: { name: 'Bentley' }, path: '/makes' },
  { data: { name: 'Cadillac' }, path: '/makes' },
  { data: { name: 'Chevrolet' }, path: '/makes' },
  { data: { name: 'Chrysler' }, path: '/makes' },
  { data: { name: 'Dodge' }, path: '/makes' },
  { data: { name: 'Fiat' }, path: '/makes' },
  { data: { name: 'Hummer' }, path: '/makes' },
  { data: { name: 'Infiniti' }, path: '/makes' },
  { data: { name: 'Isuzu' }, path: '/makes' },
  { data: { name: 'Jaguar' }, path: '/makes' },
  { data: { name: 'Jeep' }, path: '/makes' },
  { data: { name: 'Lexus' }, path: '/makes' },
  { data: { name: 'Lotus' }, path: '/makes' },
  { data: { name: 'Mitsubishi' }, path: '/makes' },
  { data: { name: 'Porsche' }, path: '/makes' },
  { data: { name: 'Range Rover' }, path: '/makes' },
  { data: { name: 'Saab' }, path: '/makes' },
  { data: { name: 'Subaru' }, path: '/makes' },
  { data: { name: 'Suzuki' }, path: '/makes' },
  { data: { name: 'Volvo' }, path: '/makes' }
];
